/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hibernate.example;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.*;
import hibernate.example.model.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

    // create an entity manager using the configuration in persistence.xml
    EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory( "jpa_provider" );
    EntityManager em = entityManagerFactory.createEntityManager();
    EntityTransaction userTransaction = em.getTransaction();
    
    // begin a SQL transaction
    userTransaction.begin();

    // Create instances of Order and FoodItem
    Order newOrder = new Order();
    newOrder.setName("Pedro's order");
    FoodItem item = new FoodItem();
    item.setName("Lasagna");

    // Initialize the relationship between both entities
    List<FoodItem> items = new ArrayList<>();
    items.add(item);
    newOrder.setIngredients(items);
    item.setAssignedOrder(newOrder);

    // save both entities: the food item is nested in the order entity
    em.persist(newOrder);

    // commit the transaction to the database
    userTransaction.commit();

    // query and print all food items
    List<FoodItem> ingredientQR = em.createQuery("select C from FoodItem C", FoodItem.class)
    .getResultList();
    ingredientQR.stream().forEach(System.out::println);

    em.close();
    entityManagerFactory.close();
    
    }
}
