/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package chapter3;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Endpoint;

@WebService
@SOAPBinding
interface HelloService {
	@WebMethod
	String sayHello(String content);
}

@WebService(endpointInterface = "com.wstutorial.ws.HelloWorld")
class HelloWorldImpl implements HelloService {

	@Override
	public String sayHello(String name) {
		return "Hello " + name + " !";
	}

}


class App {
  public static void main(String[] args) {
		Endpoint.publish("http://localhost:8080/ws/helloworld", new HelloWorldImpl());
		System.out.println("Service is running");
	}
}
